### ISSUE TITLE
Update QGreenland plugin metadata in QGIS plugin repository

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland-plugin#61]
* Mark as deprecated in the QGIS plugins interface
* Update description to indicate no longer supported.

**Comment by trey-stafford** [comment]
I updated the plugin's description and about to indicate that the plugin is no longer supported. I also marked the plugin as deprecated. See here: https://plugins.qgis.org/plugins/qgreenland/
